name: Update Top Contributors
on:
    workflow_dispatch:      # Allow manual trigger

jobs:
    update-contributors:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Generate Top Contributors
                uses: ishakhorski/top-contributors-action@v2
                with:
                    token: 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

            - name: Commit and push if changed
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    git add CONTRIBUTORS.md
                    git commit -m "Update top contributors" || exit 0
                    git push
